# Generated by Django 5.2.3 on 2026-03-22 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voteitem',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
